config/routes.rb
Stampede::Application.routes.draw do

  resources :loan_servicers

  resources :loan_lenders

  root :to => 'home#index'
  get 'find' => 'home#find', as: :find_product
  post 'result' => 'home#result', as: :show_products
  
  resources :loan_products

  

end

app/models/loan_product.rb
# Usage:
# 
#  p = LoanProduct.find_by_slug("SFL-1")
#  
#  # set loan size in dolars
#  p.loan_size = 10000
#  
#  # get any calculation
#  
#  p.get_monthly_payment_min
#  p.get_total_cost_min
#  

class LoanProduct < ActiveRecord::Base
  
  validates :slug, :presence => true
  
  has_many :loan_product_attributes
  has_many :loan_attributes, through: :loan_product_attributes
  
  belongs_to :loan_lender
  belongs_to :loan_servicer
  
  attr_accessor :loan_size

  PRIVATE = 1
  FEDERAL = 2
  PRIVATE_AND_FEDERAL = 3
  
  def get_apr_min
    return false if min_repayment_rate.nil? or auto_debit_discount.nil? or loyality_discount.nil?
    min_repayment_rate - (auto_debit_discount  + loyality_discount)
  end
  
  def get_apr_max    
    return false if max_repayment_rate.nil? or auto_debit_discount.nil? or loyality_discount.nil?
    max_repayment_rate - (auto_debit_discount  + loyality_discount)
  end
    
  def get_monthly_payment_min
    return false if loan_size.nil? or get_loan_term.nil? or !get_apr_min or get_loan_term.nil?
    ((loan_size * (get_apr_min/1200) * (1 + (get_apr_min/1200) ) ** (12*get_loan_term)) / (( 1 + (get_apr_min/1200) ) ** (12*get_loan_term)-1)).to_f.round(2)
  end
  
  def get_monthly_payment_max
    return false if loan_size.nil? or get_loan_term.nil? or !get_apr_min or get_loan_term.nil?
    ((loan_size * (max_repayment_rate/1200) * (1 + (max_repayment_rate/1200) ) ** (12*get_loan_term)) / (( 1 + (max_repayment_rate/1200) ) ** (12*get_loan_term)-1)).to_f.round(2)
  end
  
  def get_total_cost_min
    return false if loan_size.nil? or get_loan_term.nil? or !get_monthly_payment_min
    (get_monthly_payment_min*12*get_loan_term).round(2)
  end
  
  def get_total_cost_max
    return false if loan_size.nil? or get_loan_term.nil? or !get_monthly_payment_max
    (get_monthly_payment_max*12*get_loan_term).round(2)
  end
  
  def get_loan_term
    return nil unless loan_term_attr = LoanAttribute.find_by_name("loan-term")
    return nil unless loan_term = loan_product_attributes.find_by_loan_attribute_id(loan_term_attr)
    loan_term.value
  end
  
  def get_loan_type
    return nil unless loan_type_attr = LoanAttribute.find_by_name("loan-type")
    return nil unless loan_type = loan_product_attributes.find_by_loan_attribute_id(loan_type_attr)
    loan_type.value
  end
  
end

app/controllers/loan_products_controller.rb
class LoanProductsController < ApplicationController
  before_action :set_loan_product, only: [:show, :edit, :update, :destroy]
  before_action :get_loan_attributes

  # GET /loan_products
  # GET /loan_products.json
  def index
    @loan_products = LoanProduct.all
  end

  # GET /loan_products/1
  # GET /loan_products/1.json
  def show
    @loan_product.loan_size = params[:loan_size].to_i
  end

  # GET /loan_products/new
  def new
    @loan_product = LoanProduct.new
    @loan_product.loan_product_attributes.new(LoanAttribute.all.map{|a| {:loan_attribute => a, :value => 0} })
  end

  # GET /loan_products/1/edit
  def edit
    @loan_product_attributes = @loan_product.loan_product_attributes
  end

  # POST /loan_products
  # POST /loan_products.json
  def create
    @loan_product = LoanProduct.new(loan_product_params)

    respond_to do |format|
      if @loan_product.save
        # save attributes for product
        loan_product_attributes_multibox_selected =  params[:loan_product_attributes_multibox] ? params[:loan_product_attributes_multibox].values.flatten : []  
        loan_product_attributes = {}
        
        LoanAttribute.all.map{|a| a.id}.each do |attr_id|
          if loan_product_attributes_multibox_selected.include?(attr_id.to_s)
            loan_product_attributes[attr_id.to_s] = 1
          elsif params[:loan_product_attributes].has_key?(attr_id.to_s)
            loan_product_attributes[attr_id.to_s] = params[:loan_product_attributes][attr_id.to_s]
          else
            loan_product_attributes[attr_id.to_s] = 0
          end
        end
        
        loan_product_attributes.each{|attribute_id, value| LoanProductAttribute.find_or_create_by_loan_product_id_and_loan_attribute_id(@loan_product.id,attribute_id).update_attribute("value",value)}               

        format.html { redirect_to @loan_product, notice: 'Loan product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @loan_product }
      else
        format.html { render action: 'new' }
        format.json { render json: @loan_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loan_products/1
  # PATCH/PUT /loan_products/1.json
  def update
    respond_to do |format|
      if @loan_product.update(loan_product_params)
        
        # save attributes for product
        loan_product_attributes_multibox_selected =  params[:loan_product_attributes_multibox].values.flatten   
        loan_product_attributes = {}
        
        LoanAttribute.all.map{|a| a.id}.each do |attr_id|
          if loan_product_attributes_multibox_selected.include?(attr_id.to_s)
            loan_product_attributes[attr_id.to_s] = 1
          elsif params[:loan_product_attributes].has_key?(attr_id.to_s)
            loan_product_attributes[attr_id.to_s] = params[:loan_product_attributes][attr_id.to_s]
          else
            loan_product_attributes[attr_id.to_s] = 0
          end
        end
        
        loan_product_attributes.each{|attribute_id, value| LoanProductAttribute.find_or_create_by_loan_product_id_and_loan_attribute_id(@loan_product.id,attribute_id).update_attribute("value",value)}
                
        format.html { redirect_to @loan_product, notice: 'Loan product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @loan_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loan_products/1
  # DELETE /loan_products/1.json
  def destroy
    @loan_product.destroy
    respond_to do |format|
      format.html { redirect_to loan_products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan_product
      @loan_product = LoanProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_product_params
      params.require(:loan_product).permit(:slug)
    end
    
    def get_loan_attributes
      @loan_attributes = LoanAttribute.all
      @loan_attribute_types = LoanAttributeType.all
    end
    
    def loan_product_params
      params.require(:loan_product).permit(:code, :name, :enabled, :slug, :loan_lender_id, :loan_servicer_id, :logo, :cosigner_release_available , :cosigner_release_note, :external_url, :auto_debit_discount, :auto_debit_discount_note, :loyality_discount, :loyality_discount_note, :type_refinanced, :interest_rate_index, :interest_rate_index_note, :min_repayment_rate, :min_repayment_rate_note, :max_repayment_rate, :max_repayment_rate_note, :origination_fee, :early_repayment_penalty, :notes, :top_header, :extra_top_summary, :summary, :disclosure, :loan_size)
    end
end

app/helpers/loan_products_helper.rb
module LoanProductsHelper
end

app/views/loan_products/_form.html.erb
<%= form_for(@loan_product) do |f| %>
  <% if @loan_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan_product.errors.count, "error") %> prohibited this loan_product from being saved:</h2>

      <ul>
      <% @loan_product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2>Loan Information</h2>

  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  
  <div class="field">
    <%= f.label :name %><br>1
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :enabled %><br>
    <%= f.label "yes" %>
    <%= f.radio_button :enabled, 1 %>
    <%= f.label "no" %>
    <%= f.radio_button :enabled, 0 %>    
  </div>

  <h4>General information</h4>

  <div class="field">
    <%= f.label "Lender" %><br>
    <%= f.select(:loan_lender_id, LoanLender.all.map{|l| [l.name,l.id] }) %>  
  </div>

  <div class="field">
    <%= f.label "Servicer" %><br>
    <%= f.select(:loan_lender_id, LoanServicer.all.map{|l| [l.name,l.id] }) %>  
  </div>

  <div class="field">
    <%= f.label :logo %><br>
    <%= f.text_field :logo %>
    <% if @loan_product.logo and @loan_product.logo.length > 0 %>
    <br/><img src="<%=@loan_product.logo%>" alt="" height="200" />
    <% end  %>
  </div>
  
  <div class="field">
    <%= f.label "Co-signer release available" %><br>
    <%= f.text_field :cosigner_release_available %> months
  </div>
  
  <div class="field">
    <%= f.label "Co-signer release note" %><br>
    <%= f.text_area :cosigner_release_note %>
  </div>

  <div class="field">
    <%= f.label :external_url %><br>
    <%= f.text_field :external_url %>
  </div>
  
  <h4>Financial summary</h4>
  
  <!--<div class="field">
    <label>Interest rate type</label><br>
    <a href="#label-loan-type">here...</a>
  </div>-->
  
  <div class="field">
    <%= f.label :auto_debit_discount %><br>
    <%= f.text_field :auto_debit_discount %> %
  </div>
  
  <div class="field">
    <%= f.label :auto_debit_discount_note %><br>
    <%= f.text_area :auto_debit_discount_note %>
  </div>
  
  <div class="field">
    <%= f.label :loyality_discount %><br>
    <%= f.text_field :loyality_discount %> %
  </div>
  
  <div class="field">
    <%= f.label :loyality_discount_note %><br>
    <%= f.text_area :loyality_discount_note %>
  </div>
  
  <!--<div class="field">
    <label>Maximum term</label><br>
    <a href="#label-loan-term">here...</a>
  </div>-->
  
  <div class="field">
    <%= f.label "Type of loans refinanced?" %><br>
    <%= f.select(:type_refinanced, [['private',1],['federal',2],['private and federal',3]] ) %>  
  </div>
  
  <h4>Rates and Fees</h4>
  
  <div class="field">
    <%= f.label :interest_rate_index %><br>
    <%= f.text_field :interest_rate_index %> %
  </div>
  
  <div class="field">
    <%= f.label :interest_rate_index_note %><br>
    <%= f.text_area :interest_rate_index_note %>
  </div>
  
  <div class="field">
    <%= f.label :min_repayment_rate %><br>
    <%= f.text_field :min_repayment_rate %> %
  </div>
  
  <div class="field">
    <%= f.label :min_repayment_rate_note %><br>
    <%= f.text_area :min_repayment_rate_note %>
  </div>
  
  <div class="field">
    <%= f.label :max_repayment_rate %><br>
    <%= f.text_field :max_repayment_rate %> %
  </div>
  
  <div class="field">
    <%= f.label :max_repayment_rate_note %><br>
    <%= f.text_area :max_repayment_rate_note %>
  </div>

  <div class="field">
    <%= f.label :origination_fee %><br>
    <%= f.text_field :origination_fee %> %
  </div>
  
  <div class="field">
    <%= f.label :early_repayment_penalty %><br>
    <%= f.text_area :early_repayment_penalty %>
  </div>
  
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  
  <h4>Summary Page</h4>
  
  <div class="field">
    <%= f.label :top_header %><br>
    <%= f.text_area :top_header %>
  </div>
  
  <div class="field">
    <%= f.label :extra_top_summary %><br>
    <%= f.text_area :extra_top_summary %>
  </div>
  
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  
  <div class="field">
    <%= f.label :disclosure %><br>
    <%= f.text_field :disclosure %>
  </div>
  
  <h2>Loan Requiments</h2>

<% if false %>
  <% last_type = 0 %>
  <% @loan_attributes.each do |a| %>
    <% unless last_type == a.loan_attribute_type_id %>
      <h4><%= a.loan_attribute_type.label %></h4>
        <% last_type = a.loan_attribute_type_id %>
    <% end %>
    
    <div class="field">
      <% value = @loan_product.loan_product_attributes.find_by_loan_attribute_id(a.id) ? @loan_product_attributes.find_by_loan_attribute_id(a.id).value : "" %>
      <% if a.loan_attribute_type.field_type == LoanAttributeType::LOGIC %>
        <label id="label-<%= a.name %>"><%= a.label %></label>:<br>
        <input type="radio" name="loan_product_attributes[<%= a.id %>]" value="1" <%= value == 1 ? "checked" : "" %> > <label>1</label> 
        <input type="radio" name="loan_product_attributes[<%= a.id %>]" value="0" <%= value == 0 ? "checked" : "" %> > <label>0</label>
      <% end %>
      <% if a.loan_attribute_type.field_type == LoanAttributeType::NUMBER %>
        <label id="label-<%= a.name %>"><%= a.label %></label>:<br>
        <input type="text" name="loan_product_attributes[<%= a.id %>]" value="<%= value %>" />
      <% end %>
      <% if a.loan_attribute_type.field_type == LoanAttributeType::LOAN_TYPE %>
        <label id="label-<%= a.name %>"><%= a.label %></label>:<br>
        <input type="radio" name="loan_product_attributes[<%= a.id %>]" value="1" <%= value == 1 ? "checked" : "" %> > <label>fixed</label> 
        <input type="radio" name="loan_product_attributes[<%= a.id %>]" value="2" <%= value == 2 ? "checked" : "" %> > <label>variable</label>
      <% end %>
    </div>
  <% end %>
<% end %>

  <% @loan_attribute_types.each do |pa| %>
    <div class="field">
      <% if pa.field_type == LoanAttributeType::LOGIC %>
        <h4><%= pa.label %></h4>
        <select name="loan_product_attributes_multibox[<%= pa.name %>][]" multiple>
          <% pa.loan_attributes.each do |a| %>
            <% value = @loan_product.loan_product_attributes.find_by_loan_attribute_id(a.id) ? @loan_product_attributes.find_by_loan_attribute_id(a.id).value : "" %>
            <option value="<%= a.id %>" <%if value==1%>selected<%end%>><%= a.label %></option>
          <% end %>
        </select>
      <% end %>
      <% if pa.field_type == LoanAttributeType::NUMBER %>
        <h4><%= pa.label %></h4>         
        <% pa.loan_attributes.each do |a| %>
          <% value = @loan_product.loan_product_attributes.find_by_loan_attribute_id(a.id) ? @loan_product_attributes.find_by_loan_attribute_id(a.id).value : "" %>
          <label><%= a.label %></label>         
          <input type="text" name="loan_product_attributes[<%= a.id %>]" value="<%= value %>" />
          <br/>
        <% end %>
      <% end %>
      <% if pa.field_type == LoanAttributeType::LOAN_TYPE %>
        <% pa.loan_attributes.each do |a| %>
          <% value = @loan_product.loan_product_attributes.find_by_loan_attribute_id(a.id) ? @loan_product_attributes.find_by_loan_attribute_id(a.id).value : "" %>
          <h4><%= pa.label %></h4>
          <input type="radio" name="loan_product_attributes[<%= a.id %>]" value="1" <%= value == 1 ? "checked" : "" %> > <label>fixed</label> 
          <input type="radio" name="loan_product_attributes[<%= a.id %>]" value="2" <%= value == 2 ? "checked" : "" %> > <label>variable</label>
        <% end %>
      <% end %>

    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
      
      
      
      
      
      
      
      
      
<% end %>

app/views/loan_products/edit.html.erb
<h1>Editing loan_product</h1>

<%= render 'form' %>

<hr>
<%= link_to 'Show', @loan_product %> | <%= link_to 'Back', loan_products_path %>

app/views/loan_products/index.html.erb
<h1>Listing loan_products</h1>

<table>
  <thead>
    <tr>
      <th>Slug</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @loan_products.each do |loan_product| %>
      <tr>
        <td><%= loan_product.slug %></td>
        <td><%= link_to 'Show', loan_product %></td>
        <td><%= link_to 'Edit', edit_loan_product_path(loan_product) %></td>
        <td><%= link_to 'Destroy', loan_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'New Loan product', new_loan_product_path %>
<br>
<hr>
<%= link_to 'Home', root_path %>

app/views/loan_products/new.html.erb
<h1>New loan_product</h1>

<%= render 'form' %>

<hr>
<%= link_to 'Back', loan_products_path %>

app/views/loan_products/show.html.erb
<p id="notice"><%= notice %></p>

<form method="get" action="">
  <fieldset>
    Use below field for calculate rates and total cost of loan<br/>
    <label for="loan_size_calculate">Loan size</label>
    <input type="text" name="loan_size" id="loan_size_calculate" value="<%=params[:loan_size]%>" />
    <input type="submit" value="calculate">
  </fieldset>
</form>


<p>
  <strong>Enabled:</strong>
  <%= @loan_product.enabled == 1 ? "yes" : "no"  %>
</p>

<h2>General information</h2>

<p>
  <strong>Lender:</strong>
  <%= @loan_product.loan_lender ? @loan_product.loan_lender.name : "not-set" %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @loan_product.slug %>
</p>

<p>
  <strong>Name:</strong>
  <%= @loan_product.name %>
</p>

<p>
  <strong>Serviced by:</strong>
  <%= @loan_product.loan_servicer ? @loan_product.loan_servicer.name : "not-set" %>
</p>

<p>
  <strong>Logo:</strong>
  <% if @loan_product.logo and @loan_product.logo.length > 0 %><img src="<%=@loan_product.logo%>" alt="" style="max-height: 200px" /><%else%>no logo<% end  %>
</p>

<p>
  <strong>Co-signer release available:</strong>
  <%= @loan_product.cosigner_release_available %>
</p>

<p>
  <strong>Co-signer release note:</strong>
  <%= @loan_product.cosigner_release_note %>
</p>

<p>
  <strong>External url:</strong>
<% if @loan_product.external_url and @loan_product.external_url.length > 0 %><a href="<%= @loan_product.external_url %>"><%= @loan_product.external_url %></a><% end  %>
</p>

<h2>Financial summary</h2>

<p>
  <strong>Interest rate type:</strong>
  <%if @loan_product.get_loan_type == 1%>Fixed<%end%>
  <%if @loan_product.get_loan_type == 2%>Variable<%end%>
</p>

<p>
  <strong>APR min:</strong>
  <%= @loan_product.get_apr_min %>%
</p>

<p>
  <strong>APR max:</strong>
  <%= @loan_product.get_apr_max %>%
</p>

<p>
  <strong>Auto debit discount:</strong>
  <%= @loan_product.auto_debit_discount %>%
</p>

<p>
  <strong>Auto debit discount note:</strong>
  <%= @loan_product.auto_debit_discount_note %>
</p>

<p>
  <strong>Loyalty discount:</strong>
  <%= @loan_product.loyality_discount %>%
</p>

<p>
  <strong>Loyalty discount note:</strong>
  <%= @loan_product.loyality_discount_note %>
</p>

<p>
  <strong>Monthly payment min:</strong>
  $<%= @loan_product.get_monthly_payment_min %>
</p>

<p>
  <strong>Monthly payment max:</strong>
  $<%= @loan_product.get_monthly_payment_max %>
</p>

<p>
  <strong>Total cost min:</strong>
  $<%= @loan_product.get_total_cost_min %>
</p>

<p>
  $<strong>Total cost max:</strong>
  $<%= @loan_product.get_total_cost_max %>
</p>

<p>
  <strong>Maximum term:</strong>
  <%= @loan_product.get_loan_term %> years
</p>

<p>
  <strong>Type of loans refinanced?</strong>
  <%if @loan_product.type_refinanced == 1%>Private<%end%>
  <%if @loan_product.type_refinanced == 2%>Federal<%end%>
  <%if @loan_product.type_refinanced == 3%>Private and federal<%end%>
</p>

<h2>Rates and Fees</h2>

<p>
  <strong>Interest rate index:</strong>
  <%= @loan_product.interest_rate_index %>%
</p>

<p>
  <strong>Interest rate index note:</strong>
  <%= @loan_product.interest_rate_index_note %>
</p>

<p>
  <strong>Min repayment rate:</strong>
  <%= @loan_product.min_repayment_rate %>%
</p>

<p>
  <strong>Min repayment rate note:</strong>
  <%= @loan_product.min_repayment_rate_note %>
</p>

<p>
  <strong>Max repayment rate:</strong>
  <%= @loan_product.max_repayment_rate %>%
</p>

<p>
  <strong>Max repayment rate note:</strong>
  <%= @loan_product.max_repayment_rate_note %>
</p>

<p>
  <strong>Origination fee:</strong>
  <%= @loan_product.origination_fee %>%
</p>

<p>
  <strong>Early repayment penalty:</strong>
  <%= @loan_product.early_repayment_penalty %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @loan_product.notes %>
</p>

<h2>Summary page</h2>

<p>
  <strong>Top header:</strong>
  <%= @loan_product.top_header %>
</p>

<p>
  <strong>Extra top summary:</strong>
  <%= @loan_product.extra_top_summary %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @loan_product.summary %>
</p>

<p>
  <strong>Disclosure:</strong>
  <%= @loan_product.disclosure %>
</p>

<hr>
<%= link_to 'Edit', edit_loan_product_path(@loan_product) %> |
<%= link_to 'Back', loan_products_path %>