config/routes.rb
Stampede::Application.routes.draw do

  resources :loan_servicers

  resources :loan_lenders

  root :to => 'home#index'
  get 'find' => 'home#find', as: :find_product
  post 'result' => 'home#result', as: :show_products
  
  resources :loan_products

  

end

app/models/loan_lender.rb
class LoanLender < ActiveRecord::Base
  
  has_many :loan_products
  
end

app/controllers/loan_lenders_controller.rb
class LoanLendersController < ApplicationController
  before_action :set_loan_lender, only: [:show, :edit, :update, :destroy]

  # GET /loan_lenders
  # GET /loan_lenders.json
  def index
    @loan_lenders = LoanLender.all
  end

  # GET /loan_lenders/1
  # GET /loan_lenders/1.json
  def show
  end

  # GET /loan_lenders/new
  def new
    @loan_lender = LoanLender.new
  end

  # GET /loan_lenders/1/edit
  def edit
  end

  # POST /loan_lenders
  # POST /loan_lenders.json
  def create
    @loan_lender = LoanLender.new(loan_lender_params)

    respond_to do |format|
      if @loan_lender.save
        format.html { redirect_to @loan_lender, notice: 'Loan lender was successfully created.' }
        format.json { render action: 'show', status: :created, location: @loan_lender }
      else
        format.html { render action: 'new' }
        format.json { render json: @loan_lender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loan_lenders/1
  # PATCH/PUT /loan_lenders/1.json
  def update
    respond_to do |format|
      if @loan_lender.update(loan_lender_params)
        format.html { redirect_to @loan_lender, notice: 'Loan lender was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @loan_lender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loan_lenders/1
  # DELETE /loan_lenders/1.json
  def destroy
    @loan_lender.destroy
    respond_to do |format|
      format.html { redirect_to loan_lenders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan_lender
      @loan_lender = LoanLender.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_lender_params
      params.require(:loan_lender).permit(:name)
    end
end

app/helpers/loan_lenders_helper.rb
module LoanLendersHelper
end

app/views/loan_lenders/_form.html.erb
<%= form_for(@loan_lender) do |f| %>
  <% if @loan_lender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan_lender.errors.count, "error") %> prohibited this loan_lender from being saved:</h2>

      <ul>
      <% @loan_lender.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/loan_lenders/edit.html.erb
<h1>Editing loan_lender</h1>

<%= render 'form' %>

<%= link_to 'Show', @loan_lender %> |
<%= link_to 'Back', loan_lenders_path %>

app/views/loan_lenders/index.html.erb
<h1>Listing loan_lenders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @loan_lenders.each do |loan_lender| %>
      <tr>
        <td><%= loan_lender.name %></td>
        <td><%= link_to 'Show', loan_lender %></td>
        <td><%= link_to 'Edit', edit_loan_lender_path(loan_lender) %></td>
        <td><%= link_to 'Destroy', loan_lender, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loan lender', new_loan_lender_path %>
<hr>
<%= link_to 'Home', root_path %>

app/views/loan_lenders/new.html.erb
<h1>New loan_lender</h1>

<%= render 'form' %>

<%= link_to 'Back', loan_lenders_path %>

app/views/loan_lenders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @loan_lender.name %>
</p>

<%= link_to 'Edit', edit_loan_lender_path(@loan_lender) %> |
<%= link_to 'Back', loan_lenders_path %>