config/routes.rb
Stampede::Application.routes.draw do

  resources :loan_servicers

  resources :loan_lenders

  root :to => 'home#index'
  get 'find' => 'home#find', as: :find_product
  post 'result' => 'home#result', as: :show_products
  
  resources :loan_products

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :get_loan_attributes, only: [:find]
  
  def index
  end
  
  def find
    @loan_products = LoanProduct.all
  end
  
  def result
    if params[:loan_attribs]
      req = LoanProductRequiment.new(params[:loan_product][:slug])
      req.assign_attributes(params[:loan_attribs])
      @product = params[:loan_product][:slug]
      @result = req.result
    end
  end
  
    private
    
    def get_loan_attributes
      @loan_attributes = LoanProductRequiment.get_attributes
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/find.html.erb
<h1>Stampede Decisioning Dashboard - Find Eligible Product Form</h1>

<%= form_tag("/result") do %>

<div class="filed">
  <label>Select product</label>
  <%= select("loan_product", "slug", @loan_products.map {|at| [ at[:slug], at[:slug] ] }, {include_blank: 'all products'}) %>  
</div>
  
  <% @loan_attributes.each do |a| %>
    <% unless ["eliminate-undergraduates","loan-term","lender-specific-rules","minimum-loan-by-states"].include?(a[:name]) %>
      <div class="filed">
        <% if a[:field_type] == 2 %>
          <label><%= a[:label] %></label>
          <%= text_field_tag "loan_attribs["+a[:name].gsub("-","_")+"]", nil %>
        <% elsif a[:field_type] == 3  %>
          <% if a[:name] == "loan-type"  %>
            <label>Loan term and type</label>
            <%= select("loan_attribs", "loan_term_and_type", ["fixed-5-years","fixed-10-years","fixed-15-years","variable"]) %>  
          <% end  %>
        <% elsif a[:field_type] == 4  %>
            <label><%= a[:label] %></label>
            <%= radio_button_tag("loan_attribs["+a[:name].gsub("-","_")+"]", "yes") %>
            <%= label_tag(:age_yes, "yes") %>
            <%= radio_button_tag("loan_attribs["+a[:name].gsub("-","_")+"]", "no") %>
            <%= label_tag(:age_no, "no") %>
        <% else %>
          <% unless a[:name] == "degree-eligible" %>
            <label><%= a[:label] %></label>
            <%= select("loan_attribs", a[:name].gsub("-","_"), a[:attributes].map {|at| [ at[:label], at[:name] ] }) %>  
          <% else %>
            <label><%= a[:label] %></label>
            <select id="loan_attribs_degree_eligible" name="loan_attribs[degree_eligible]">
              <% a[:attributes].each do |at| %>
              <option value="<%=at[:name]%>" <%if at[:disabled] == 1%>disabled="disabled" style="font-style: italic"<%end%>><%unless at[:disabled] == 1%>&nbsp;&nbsp;<%end%><%=at[:label]%></option>
              <% end %>
            </select>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <%  end %>
    <%= submit_tag("Check") %>
<%  end %>

<hr>
<%= link_to 'Home', root_path %>

app/views/home/index.html.erb
<h1>Stampede Decisioning Dashboard</h1>
<nav>
  <ul>
    <li><%= link_to "Manage Loan Products", loan_products_path %></li>
  </ul>
  <ul>
    <li><%= link_to "Find Eligible Products", find_product_path %></li>
  </ul>
  <ul>
    <li><%= link_to "Manage Loan Lenders", loan_lenders_path %></li>
    <li><%= link_to "Manage Loan Servicers", loan_servicers_path %></li>
  </ul>
</nav>

app/views/home/result.html.erb
<h1>Stampede Decisioning Dashboard - RESULT</h1>

<% if @product.length > 0  %>
  <% if @result == true %>
    Product <%= @product %> is eligible.
  <% elsif %>
    Product <%= @product %> is NOT eligible.
  <% end %>
<% elsif %>
     <% if @result.is_a? Array  %>
        List of eligible products: <%= @result.join(", ")  %>
     <% elsif %>
        There is no eligible products.
     <% end %>
<% end %>

<hr>
<%= link_to 'Home', root_path %> | <%= link_to 'New search', find_product_path  %>