config/routes.rb
Stampede::Application.routes.draw do

  resources :loan_servicers

  resources :loan_lenders

  root :to => 'home#index'
  get 'find' => 'home#find', as: :find_product
  post 'result' => 'home#result', as: :show_products
  
  resources :loan_products

  

end

app/models/loan_servicer.rb
class LoanServicer < ActiveRecord::Base
end

app/controllers/loan_servicers_controller.rb
class LoanServicersController < ApplicationController
  before_action :set_loan_servicer, only: [:show, :edit, :update, :destroy]

  # GET /loan_servicers
  # GET /loan_servicers.json
  def index
    @loan_servicers = LoanServicer.all
  end

  # GET /loan_servicers/1
  # GET /loan_servicers/1.json
  def show
  end

  # GET /loan_servicers/new
  def new
    @loan_servicer = LoanServicer.new
  end

  # GET /loan_servicers/1/edit
  def edit
  end

  # POST /loan_servicers
  # POST /loan_servicers.json
  def create
    @loan_servicer = LoanServicer.new(loan_servicer_params)

    respond_to do |format|
      if @loan_servicer.save
        format.html { redirect_to @loan_servicer, notice: 'Loan servicer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @loan_servicer }
      else
        format.html { render action: 'new' }
        format.json { render json: @loan_servicer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loan_servicers/1
  # PATCH/PUT /loan_servicers/1.json
  def update
    respond_to do |format|
      if @loan_servicer.update(loan_servicer_params)
        format.html { redirect_to @loan_servicer, notice: 'Loan servicer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @loan_servicer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loan_servicers/1
  # DELETE /loan_servicers/1.json
  def destroy
    @loan_servicer.destroy
    respond_to do |format|
      format.html { redirect_to loan_servicers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan_servicer
      @loan_servicer = LoanServicer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_servicer_params
      params.require(:loan_servicer).permit(:name)
    end
end

app/helpers/loan_servicers_helper.rb
module LoanServicersHelper
end

app/views/loan_servicers/_form.html.erb
<%= form_for(@loan_servicer) do |f| %>
  <% if @loan_servicer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan_servicer.errors.count, "error") %> prohibited this loan_servicer from being saved:</h2>

      <ul>
      <% @loan_servicer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/loan_servicers/edit.html.erb
<h1>Editing loan_servicer</h1>

<%= render 'form' %>

<%= link_to 'Show', @loan_servicer %> |
<%= link_to 'Back', loan_servicers_path %>

app/views/loan_servicers/index.html.erb
<h1>Listing loan_servicers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @loan_servicers.each do |loan_servicer| %>
      <tr>
        <td><%= loan_servicer.name %></td>
        <td><%= link_to 'Show', loan_servicer %></td>
        <td><%= link_to 'Edit', edit_loan_servicer_path(loan_servicer) %></td>
        <td><%= link_to 'Destroy', loan_servicer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loan servicer', new_loan_servicer_path %>
<hr>
<%= link_to 'Home', root_path %>

app/views/loan_servicers/new.html.erb
<h1>New loan_servicer</h1>

<%= render 'form' %>

<%= link_to 'Back', loan_servicers_path %>

app/views/loan_servicers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @loan_servicer.name %>
</p>

<%= link_to 'Edit', edit_loan_servicer_path(@loan_servicer) %> |
<%= link_to 'Back', loan_servicers_path %>